//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraSiglo21.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adicciones
    {
        public Adicciones()
        {
            this.Adicciones_Cliente = new HashSet<Adicciones_Cliente>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Codigo { get; set; }
    
        public virtual ICollection<Adicciones_Cliente> Adicciones_Cliente { get; set; }
    }
}
