//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraSiglo21.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bitacora_Login
    {
        public int ID { get; set; }
        public string ID_Usuario { get; set; }
        public System.DateTime Fecha_Ultimo_Login { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
