//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraSiglo21.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class siglo21Entities1 : DbContext
    {
        public siglo21Entities1()
            : base("name=siglo21Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Adicciones> Adicciones { get; set; }
        public DbSet<Adicciones_Cliente> Adicciones_Cliente { get; set; }
        public DbSet<Bitacora_Login> Bitacora_Login { get; set; }
        public DbSet<Canton> Canton { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Cobertura_Poliza> Cobertura_Poliza { get; set; }
        public DbSet<Distrito> Distrito { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<Provincia> Provincia { get; set; }
        public DbSet<Puesto_Trabajo> Puesto_Trabajo { get; set; }
        public DbSet<Registro_Poliza> Registro_Poliza { get; set; }
        public DbSet<Tipo_Usuario> Tipo_Usuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    
        public virtual int sp_EliminaRegistroAdicciones(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroAdicciones", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroAdicciones_Cliente(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroAdicciones_Cliente", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroBitacora_Login(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroBitacora_Login", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroCanton(Nullable<int> iD_Canton)
        {
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroCanton", iD_CantonParameter);
        }
    
        public virtual int sp_EliminaRegistroCliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroCliente", cedulaParameter);
        }
    
        public virtual int sp_EliminaRegistroCobertura_Poliza(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroCobertura_Poliza", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroDistrito(Nullable<int> iD_Distrito)
        {
            var iD_DistritoParameter = iD_Distrito.HasValue ?
                new ObjectParameter("ID_Distrito", iD_Distrito) :
                new ObjectParameter("ID_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroDistrito", iD_DistritoParameter);
        }
    
        public virtual int sp_EliminaRegistroEmpleado(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroEmpleado", cedulaParameter);
        }
    
        public virtual int sp_EliminaRegistroPoliza(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroPoliza", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroProvincia(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroProvincia", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroPuesto_Trabajo(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroPuesto_Trabajo", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroTipo_Usuario(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroTipo_Usuario", iDParameter);
        }
    
        public virtual int sp_EliminaRegistroUsuario(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminaRegistroUsuario", iDParameter);
        }
    
        public virtual int sp_InsertaAdiccion(string nombre, string codigo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaAdiccion", nombreParameter, codigoParameter);
        }
    
        public virtual int sp_InsertaAdiccion_Cliente(Nullable<int> iD_Adiccion, string cedula)
        {
            var iD_AdiccionParameter = iD_Adiccion.HasValue ?
                new ObjectParameter("ID_Adiccion", iD_Adiccion) :
                new ObjectParameter("ID_Adiccion", typeof(int));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaAdiccion_Cliente", iD_AdiccionParameter, cedulaParameter);
        }
    
        public virtual int sp_InsertaBitacora_Login(Nullable<int> iD, Nullable<int> iD_Usuario, Nullable<System.DateTime> fecha_Ultimo_Login)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario.HasValue ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(int));
    
            var fecha_Ultimo_LoginParameter = fecha_Ultimo_Login.HasValue ?
                new ObjectParameter("Fecha_Ultimo_Login", fecha_Ultimo_Login) :
                new ObjectParameter("Fecha_Ultimo_Login", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaBitacora_Login", iDParameter, iD_UsuarioParameter, fecha_Ultimo_LoginParameter);
        }
    
        public virtual int sp_InsertaCanton(string nombre, Nullable<int> iD_Provincia)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCanton", nombreParameter, iD_ProvinciaParameter);
        }
    
        public virtual int sp_InsertaCliente(string cedula, string genero, Nullable<System.DateTime> fecha_Nacimiento, string nombre, string apellido1, string apellido2, string direccion, string telefono1, string telefono2, string correo_Electronico, Nullable<int> iD_Provincia, Nullable<int> iD_Canton, Nullable<int> iD_Distrito)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            var iD_DistritoParameter = iD_Distrito.HasValue ?
                new ObjectParameter("ID_Distrito", iD_Distrito) :
                new ObjectParameter("ID_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCliente", cedulaParameter, generoParameter, fecha_NacimientoParameter, nombreParameter, apellido1Parameter, apellido2Parameter, direccionParameter, telefono1Parameter, telefono2Parameter, correo_ElectronicoParameter, iD_ProvinciaParameter, iD_CantonParameter, iD_DistritoParameter);
        }
    
        public virtual int sp_InsertaCobertura_Poliza(string nombre, string descripcion, Nullable<double> porcentaje)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var porcentajeParameter = porcentaje.HasValue ?
                new ObjectParameter("Porcentaje", porcentaje) :
                new ObjectParameter("Porcentaje", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaCobertura_Poliza", nombreParameter, descripcionParameter, porcentajeParameter);
        }
    
        public virtual int sp_InsertaDistrito(string nombre, Nullable<int> iD_Canton)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaDistrito", nombreParameter, iD_CantonParameter);
        }
    
        public virtual int sp_InsertaEmpleado(string cedula, string genero, Nullable<System.DateTime> fecha_Nacimiento, string nombre, string apellido1, string apellido2, string direccion, string telefono1, string telefono2, string correo_Electronico, Nullable<int> iD_Provincia, Nullable<int> iD_Canton, Nullable<int> iD_Distrito, Nullable<int> puesto)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            var iD_DistritoParameter = iD_Distrito.HasValue ?
                new ObjectParameter("ID_Distrito", iD_Distrito) :
                new ObjectParameter("ID_Distrito", typeof(int));
    
            var puestoParameter = puesto.HasValue ?
                new ObjectParameter("Puesto", puesto) :
                new ObjectParameter("Puesto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaEmpleado", cedulaParameter, generoParameter, fecha_NacimientoParameter, nombreParameter, apellido1Parameter, apellido2Parameter, direccionParameter, telefono1Parameter, telefono2Parameter, correo_ElectronicoParameter, iD_ProvinciaParameter, iD_CantonParameter, iD_DistritoParameter, puestoParameter);
        }
    
        public virtual int sp_InsertaProvincia(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaProvincia", nombreParameter);
        }
    
        public virtual int sp_InsertaPuesto_Trabajo(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaPuesto_Trabajo", descripcionParameter);
        }
    
        public virtual int sp_InsertaRegistro_Poliza(Nullable<double> monto_Asegurado, Nullable<double> porcentaje_Cobertura, Nullable<int> numero_Adicciones, Nullable<double> monto_Adicciones, Nullable<double> prima_Antes_Impuesto, Nullable<double> impuestos, Nullable<double> prima_Final, Nullable<int> iD_Cobertura_Poliza, string iD_Cliente)
        {
            var monto_AseguradoParameter = monto_Asegurado.HasValue ?
                new ObjectParameter("Monto_Asegurado", monto_Asegurado) :
                new ObjectParameter("Monto_Asegurado", typeof(double));
    
            var porcentaje_CoberturaParameter = porcentaje_Cobertura.HasValue ?
                new ObjectParameter("Porcentaje_Cobertura", porcentaje_Cobertura) :
                new ObjectParameter("Porcentaje_Cobertura", typeof(double));
    
            var numero_AdiccionesParameter = numero_Adicciones.HasValue ?
                new ObjectParameter("Numero_Adicciones", numero_Adicciones) :
                new ObjectParameter("Numero_Adicciones", typeof(int));
    
            var monto_AdiccionesParameter = monto_Adicciones.HasValue ?
                new ObjectParameter("Monto_Adicciones", monto_Adicciones) :
                new ObjectParameter("Monto_Adicciones", typeof(double));
    
            var prima_Antes_ImpuestoParameter = prima_Antes_Impuesto.HasValue ?
                new ObjectParameter("Prima_Antes_Impuesto", prima_Antes_Impuesto) :
                new ObjectParameter("Prima_Antes_Impuesto", typeof(double));
    
            var impuestosParameter = impuestos.HasValue ?
                new ObjectParameter("Impuestos", impuestos) :
                new ObjectParameter("Impuestos", typeof(double));
    
            var prima_FinalParameter = prima_Final.HasValue ?
                new ObjectParameter("Prima_Final", prima_Final) :
                new ObjectParameter("Prima_Final", typeof(double));
    
            var iD_Cobertura_PolizaParameter = iD_Cobertura_Poliza.HasValue ?
                new ObjectParameter("ID_Cobertura_Poliza", iD_Cobertura_Poliza) :
                new ObjectParameter("ID_Cobertura_Poliza", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaRegistro_Poliza", monto_AseguradoParameter, porcentaje_CoberturaParameter, numero_AdiccionesParameter, monto_AdiccionesParameter, prima_Antes_ImpuestoParameter, impuestosParameter, prima_FinalParameter, iD_Cobertura_PolizaParameter, iD_ClienteParameter);
        }
    
        public virtual int sp_InsertaTipo_Usuario(string descripcion)
        {
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaTipo_Usuario", descripcionParameter);
        }
    
        public virtual int sp_InsertaUsuario(string usuario, string contrasena, Nullable<int> tipo_Usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("Contrasena", contrasena) :
                new ObjectParameter("Contrasena", typeof(string));
    
            var tipo_UsuarioParameter = tipo_Usuario.HasValue ?
                new ObjectParameter("Tipo_Usuario", tipo_Usuario) :
                new ObjectParameter("Tipo_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaUsuario", usuarioParameter, contrasenaParameter, tipo_UsuarioParameter);
        }
    
        public virtual int sp_ModificaRegistroAdiccion(Nullable<int> iD, string nombre, string codigo)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroAdiccion", iDParameter, nombreParameter, codigoParameter);
        }
    
        public virtual int sp_ModificaRegistroAdiccion_Cliente(Nullable<int> iD, Nullable<int> iD_Adiccion, string iD_Cliente)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_AdiccionParameter = iD_Adiccion.HasValue ?
                new ObjectParameter("ID_Adiccion", iD_Adiccion) :
                new ObjectParameter("ID_Adiccion", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroAdiccion_Cliente", iDParameter, iD_AdiccionParameter, iD_ClienteParameter);
        }
    
        public virtual int sp_ModificaRegistroBitacora_Login(Nullable<int> iD, string iD_Usuario, Nullable<System.DateTime> fecha)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var iD_UsuarioParameter = iD_Usuario != null ?
                new ObjectParameter("ID_Usuario", iD_Usuario) :
                new ObjectParameter("ID_Usuario", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroBitacora_Login", iDParameter, iD_UsuarioParameter, fechaParameter);
        }
    
        public virtual int sp_ModificaRegistroCanton(Nullable<int> iD, string nombre, Nullable<int> iD_Provincia)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroCanton", iDParameter, nombreParameter, iD_ProvinciaParameter);
        }
    
        public virtual int sp_ModificaRegistroCliente(string iD_ClienteCed, string cedula, string genero, Nullable<System.DateTime> fecha_Nacimiento, string nombre, string apellido1, string apellido2, string direccion, string telefono1, string telefono2, string correo_Electronico, Nullable<int> iD_Provincia, Nullable<int> iD_Canton, Nullable<int> iD_Distrito)
        {
            var iD_ClienteCedParameter = iD_ClienteCed != null ?
                new ObjectParameter("ID_ClienteCed", iD_ClienteCed) :
                new ObjectParameter("ID_ClienteCed", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            var iD_DistritoParameter = iD_Distrito.HasValue ?
                new ObjectParameter("ID_Distrito", iD_Distrito) :
                new ObjectParameter("ID_Distrito", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroCliente", iD_ClienteCedParameter, cedulaParameter, generoParameter, fecha_NacimientoParameter, nombreParameter, apellido1Parameter, apellido2Parameter, direccionParameter, telefono1Parameter, telefono2Parameter, correo_ElectronicoParameter, iD_ProvinciaParameter, iD_CantonParameter, iD_DistritoParameter);
        }
    
        public virtual int sp_ModificaRegistroCobertura_Poliza(Nullable<int> iD, string nombre, string descripcion, Nullable<double> porcentaje)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var porcentajeParameter = porcentaje.HasValue ?
                new ObjectParameter("Porcentaje", porcentaje) :
                new ObjectParameter("Porcentaje", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroCobertura_Poliza", iDParameter, nombreParameter, descripcionParameter, porcentajeParameter);
        }
    
        public virtual int sp_ModificaRegistroDistrito(Nullable<int> iD, string nombre, Nullable<int> iD_Canton)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroDistrito", iDParameter, nombreParameter, iD_CantonParameter);
        }
    
        public virtual int sp_ModificaRegistroEmpleado(string iD_Empleado, string cedula, string genero, Nullable<System.DateTime> fecha_Nacimiento, string nombre, string apellido1, string apellido2, string direccion, string telefono1, string telefono2, string correo_Electronico, Nullable<int> iD_Provincia, Nullable<int> iD_Canton, Nullable<int> iD_Distrito, Nullable<int> puesto)
        {
            var iD_EmpleadoParameter = iD_Empleado != null ?
                new ObjectParameter("ID_Empleado", iD_Empleado) :
                new ObjectParameter("ID_Empleado", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correo_ElectronicoParameter = correo_Electronico != null ?
                new ObjectParameter("Correo_Electronico", correo_Electronico) :
                new ObjectParameter("Correo_Electronico", typeof(string));
    
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            var iD_CantonParameter = iD_Canton.HasValue ?
                new ObjectParameter("ID_Canton", iD_Canton) :
                new ObjectParameter("ID_Canton", typeof(int));
    
            var iD_DistritoParameter = iD_Distrito.HasValue ?
                new ObjectParameter("ID_Distrito", iD_Distrito) :
                new ObjectParameter("ID_Distrito", typeof(int));
    
            var puestoParameter = puesto.HasValue ?
                new ObjectParameter("Puesto", puesto) :
                new ObjectParameter("Puesto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroEmpleado", iD_EmpleadoParameter, cedulaParameter, generoParameter, fecha_NacimientoParameter, nombreParameter, apellido1Parameter, apellido2Parameter, direccionParameter, telefono1Parameter, telefono2Parameter, correo_ElectronicoParameter, iD_ProvinciaParameter, iD_CantonParameter, iD_DistritoParameter, puestoParameter);
        }
    
        public virtual int sp_ModificaRegistroPoliza(Nullable<int> iD, Nullable<double> monto_Asegurado, Nullable<double> porcentaje_Cobertura, Nullable<int> numero_Adicciones, Nullable<double> monto_Adicciones, Nullable<double> pRima_Antes_Impuestos, Nullable<double> impuestos, Nullable<double> prima_Final, Nullable<int> iD_Cobertura_Poliza, string iD_Cliente)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var monto_AseguradoParameter = monto_Asegurado.HasValue ?
                new ObjectParameter("Monto_Asegurado", monto_Asegurado) :
                new ObjectParameter("Monto_Asegurado", typeof(double));
    
            var porcentaje_CoberturaParameter = porcentaje_Cobertura.HasValue ?
                new ObjectParameter("Porcentaje_Cobertura", porcentaje_Cobertura) :
                new ObjectParameter("Porcentaje_Cobertura", typeof(double));
    
            var numero_AdiccionesParameter = numero_Adicciones.HasValue ?
                new ObjectParameter("Numero_Adicciones", numero_Adicciones) :
                new ObjectParameter("Numero_Adicciones", typeof(int));
    
            var monto_AdiccionesParameter = monto_Adicciones.HasValue ?
                new ObjectParameter("Monto_Adicciones", monto_Adicciones) :
                new ObjectParameter("Monto_Adicciones", typeof(double));
    
            var pRima_Antes_ImpuestosParameter = pRima_Antes_Impuestos.HasValue ?
                new ObjectParameter("PRima_Antes_Impuestos", pRima_Antes_Impuestos) :
                new ObjectParameter("PRima_Antes_Impuestos", typeof(double));
    
            var impuestosParameter = impuestos.HasValue ?
                new ObjectParameter("Impuestos", impuestos) :
                new ObjectParameter("Impuestos", typeof(double));
    
            var prima_FinalParameter = prima_Final.HasValue ?
                new ObjectParameter("Prima_Final", prima_Final) :
                new ObjectParameter("Prima_Final", typeof(double));
    
            var iD_Cobertura_PolizaParameter = iD_Cobertura_Poliza.HasValue ?
                new ObjectParameter("ID_Cobertura_Poliza", iD_Cobertura_Poliza) :
                new ObjectParameter("ID_Cobertura_Poliza", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroPoliza", iDParameter, monto_AseguradoParameter, porcentaje_CoberturaParameter, numero_AdiccionesParameter, monto_AdiccionesParameter, pRima_Antes_ImpuestosParameter, impuestosParameter, prima_FinalParameter, iD_Cobertura_PolizaParameter, iD_ClienteParameter);
        }
    
        public virtual int sp_ModificaRegistroProvincia(Nullable<int> iD_Provincia, string nombre)
        {
            var iD_ProvinciaParameter = iD_Provincia.HasValue ?
                new ObjectParameter("ID_Provincia", iD_Provincia) :
                new ObjectParameter("ID_Provincia", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroProvincia", iD_ProvinciaParameter, nombreParameter);
        }
    
        public virtual int sp_ModificaRegistroPuesto_Trabajo(Nullable<int> iD, string descripcion)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroPuesto_Trabajo", iDParameter, descripcionParameter);
        }
    
        public virtual int sp_ModificaRegistroTipo_Usuario(Nullable<int> iD, string descripcion)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroTipo_Usuario", iDParameter, descripcionParameter);
        }
    
        public virtual int sp_ModificaRegistroUsuario(Nullable<int> iD, string usuario, string contrasena, Nullable<int> tipo_Usuario)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var tipo_UsuarioParameter = tipo_Usuario.HasValue ?
                new ObjectParameter("Tipo_Usuario", tipo_Usuario) :
                new ObjectParameter("Tipo_Usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaRegistroUsuario", iDParameter, usuarioParameter, contrasenaParameter, tipo_UsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Selecciona_Todas_Adicciones_Result> sp_Selecciona_Todas_Adicciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Selecciona_Todas_Adicciones_Result>("sp_Selecciona_Todas_Adicciones");
        }
    
        public virtual ObjectResult<sp_Selecciona_Una_Adiccion_Result> sp_Selecciona_Una_Adiccion(string cogigo)
        {
            var cogigoParameter = cogigo != null ?
                new ObjectParameter("Cogigo", cogigo) :
                new ObjectParameter("Cogigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Selecciona_Una_Adiccion_Result>("sp_Selecciona_Una_Adiccion", cogigoParameter);
        }
    
        public virtual ObjectResult<sp_Selecciona_Una_Cobertura_Poliza_Result> sp_Selecciona_Una_Cobertura_Poliza(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Selecciona_Una_Cobertura_Poliza_Result>("sp_Selecciona_Una_Cobertura_Poliza", nombreParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaAdicciones_Cliente_Result> sp_SeleccionaAdicciones_Cliente(string cedulaCliente)
        {
            var cedulaClienteParameter = cedulaCliente != null ?
                new ObjectParameter("CedulaCliente", cedulaCliente) :
                new ObjectParameter("CedulaCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaAdicciones_Cliente_Result>("sp_SeleccionaAdicciones_Cliente", cedulaClienteParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaCliente_Result> sp_SeleccionaCliente(string iD_Cliente)
        {
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaCliente_Result>("sp_SeleccionaCliente", iD_ClienteParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaInfomacionTablaProvincia_Result> sp_SeleccionaInfomacionTablaProvincia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaInfomacionTablaProvincia_Result>("sp_SeleccionaInfomacionTablaProvincia");
        }
    
        public virtual ObjectResult<sp_SeleccionaRegistroPoliza_Result> sp_SeleccionaRegistroPoliza(string cedulaCliente)
        {
            var cedulaClienteParameter = cedulaCliente != null ?
                new ObjectParameter("CedulaCliente", cedulaCliente) :
                new ObjectParameter("CedulaCliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaRegistroPoliza_Result>("sp_SeleccionaRegistroPoliza", cedulaClienteParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaTodo_Clientes_Result> sp_SeleccionaTodo_Clientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaTodo_Clientes_Result>("sp_SeleccionaTodo_Clientes");
        }
    
        public virtual ObjectResult<sp_SeleccionaTodo_Cobertura_Poliza_Result> sp_SeleccionaTodo_Cobertura_Poliza()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaTodo_Cobertura_Poliza_Result>("sp_SeleccionaTodo_Cobertura_Poliza");
        }
    
        public virtual ObjectResult<string> sp_SeleccionaCantones(Nullable<int> iDProvincia)
        {
            var iDProvinciaParameter = iDProvincia.HasValue ?
                new ObjectParameter("IDProvincia", iDProvincia) :
                new ObjectParameter("IDProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_SeleccionaCantones", iDProvinciaParameter);
        }
    
        public virtual ObjectResult<string> sp_SeleccionaDistritos(Nullable<int> iDCanton)
        {
            var iDCantonParameter = iDCanton.HasValue ?
                new ObjectParameter("IDCanton", iDCanton) :
                new ObjectParameter("IDCanton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_SeleccionaDistritos", iDCantonParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaCantonesProvincia_Result> sp_SeleccionaCantonesProvincia(Nullable<int> iDProvincia)
        {
            var iDProvinciaParameter = iDProvincia.HasValue ?
                new ObjectParameter("IDProvincia", iDProvincia) :
                new ObjectParameter("IDProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaCantonesProvincia_Result>("sp_SeleccionaCantonesProvincia", iDProvinciaParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaDistritosPorCanton_Result> sp_SeleccionaDistritosPorCanton(Nullable<int> iDCanton)
        {
            var iDCantonParameter = iDCanton.HasValue ?
                new ObjectParameter("IDCanton", iDCanton) :
                new ObjectParameter("IDCanton", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaDistritosPorCanton_Result>("sp_SeleccionaDistritosPorCanton", iDCantonParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaCantonesProvincia1_Result> sp_SeleccionaCantonesProvincia1(Nullable<int> iDProvincia)
        {
            var iDProvinciaParameter = iDProvincia.HasValue ?
                new ObjectParameter("IDProvincia", iDProvincia) :
                new ObjectParameter("IDProvincia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaCantonesProvincia1_Result>("sp_SeleccionaCantonesProvincia1", iDProvinciaParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaClienteCedula_Result> sp_SeleccionaClienteCedula(string iD_Cliente)
        {
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaClienteCedula_Result>("sp_SeleccionaClienteCedula", iD_ClienteParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaUnaCoberturaPoliza_Result> sp_SeleccionaUnaCoberturaPoliza(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaUnaCoberturaPoliza_Result>("sp_SeleccionaUnaCoberturaPoliza", nombreParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaClientesBusqueda_Result> sp_SeleccionaClientesBusqueda(string nombre, string apellido1, string apellido2, string cedula)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaClientesBusqueda_Result>("sp_SeleccionaClientesBusqueda", nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter);
        }
    
        public virtual ObjectResult<sp_ClientesBusquedas_Result> sp_ClientesBusquedas(string nombre, string apellido1, string apellido2, string cedula)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("apellido1", apellido1) :
                new ObjectParameter("apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("apellido2", apellido2) :
                new ObjectParameter("apellido2", typeof(string));
    
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ClientesBusquedas_Result>("sp_ClientesBusquedas", nombreParameter, apellido1Parameter, apellido2Parameter, cedulaParameter);
        }
    
        public virtual ObjectResult<sp_CoberturaPolizaBusqueda_Result> sp_CoberturaPolizaBusqueda(string nombre, string descripcion)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CoberturaPolizaBusqueda_Result>("sp_CoberturaPolizaBusqueda", nombreParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<sp_AdiccionesBusquedas_Result> sp_AdiccionesBusquedas(string nombre, string codigo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AdiccionesBusquedas_Result>("sp_AdiccionesBusquedas", nombreParameter, codigoParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaUnaAdiccion_Result> sp_SeleccionaUnaAdiccion(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaUnaAdiccion_Result>("sp_SeleccionaUnaAdiccion", iDParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaUnaAdiccionCodigo_Result> sp_SeleccionaUnaAdiccionCodigo(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaUnaAdiccionCodigo_Result>("sp_SeleccionaUnaAdiccionCodigo", codigoParameter);
        }
    
        public virtual int sp_BusquedaClienteAdiccionesRepetidos(Nullable<int> id_Adiccion, string ced_Cliente)
        {
            var id_AdiccionParameter = id_Adiccion.HasValue ?
                new ObjectParameter("Id_Adiccion", id_Adiccion) :
                new ObjectParameter("Id_Adiccion", typeof(int));
    
            var ced_ClienteParameter = ced_Cliente != null ?
                new ObjectParameter("Ced_Cliente", ced_Cliente) :
                new ObjectParameter("Ced_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BusquedaClienteAdiccionesRepetidos", id_AdiccionParameter, ced_ClienteParameter);
        }
    
        public virtual int sp_ClienteAdiccionesDuplicados(Nullable<int> id_Adiccion, string ced_Cliente, ObjectParameter resultado)
        {
            var id_AdiccionParameter = id_Adiccion.HasValue ?
                new ObjectParameter("Id_Adiccion", id_Adiccion) :
                new ObjectParameter("Id_Adiccion", typeof(int));
    
            var ced_ClienteParameter = ced_Cliente != null ?
                new ObjectParameter("Ced_Cliente", ced_Cliente) :
                new ObjectParameter("Ced_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ClienteAdiccionesDuplicados", id_AdiccionParameter, ced_ClienteParameter, resultado);
        }
    
        public virtual ObjectResult<sp_AdiccionesClienteDuplicados_Result> sp_AdiccionesClienteDuplicados(Nullable<int> id_Adiccion, string ced_Cliente)
        {
            var id_AdiccionParameter = id_Adiccion.HasValue ?
                new ObjectParameter("Id_Adiccion", id_Adiccion) :
                new ObjectParameter("Id_Adiccion", typeof(int));
    
            var ced_ClienteParameter = ced_Cliente != null ?
                new ObjectParameter("Ced_Cliente", ced_Cliente) :
                new ObjectParameter("Ced_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AdiccionesClienteDuplicados_Result>("sp_AdiccionesClienteDuplicados", id_AdiccionParameter, ced_ClienteParameter);
        }
    
        public virtual ObjectResult<sp_SeleccionaTodasAdicciones_Result> sp_SeleccionaTodasAdicciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaTodasAdicciones_Result>("sp_SeleccionaTodasAdicciones");
        }
    
        public virtual ObjectResult<sp_SeleccionaAdicciones_Result> sp_SeleccionaAdicciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SeleccionaAdicciones_Result>("sp_SeleccionaAdicciones");
        }
    
        public virtual ObjectResult<sp_AdiccionesClienteBuscaDuplicados_Result> sp_AdiccionesClienteBuscaDuplicados(Nullable<int> id_Adiccion, string ced_Cliente)
        {
            var id_AdiccionParameter = id_Adiccion.HasValue ?
                new ObjectParameter("Id_Adiccion", id_Adiccion) :
                new ObjectParameter("Id_Adiccion", typeof(int));
    
            var ced_ClienteParameter = ced_Cliente != null ?
                new ObjectParameter("Ced_Cliente", ced_Cliente) :
                new ObjectParameter("Ced_Cliente", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AdiccionesClienteBuscaDuplicados_Result>("sp_AdiccionesClienteBuscaDuplicados", id_AdiccionParameter, ced_ClienteParameter);
        }
    
        public virtual ObjectResult<sp_AdiccionesClienteBusqueda_Result> sp_AdiccionesClienteBusqueda(string cedulaCLiente, string codigoAdiccion)
        {
            var cedulaCLienteParameter = cedulaCLiente != null ?
                new ObjectParameter("CedulaCLiente", cedulaCLiente) :
                new ObjectParameter("CedulaCLiente", typeof(string));
    
            var codigoAdiccionParameter = codigoAdiccion != null ?
                new ObjectParameter("CodigoAdiccion", codigoAdiccion) :
                new ObjectParameter("CodigoAdiccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AdiccionesClienteBusqueda_Result>("sp_AdiccionesClienteBusqueda", cedulaCLienteParameter, codigoAdiccionParameter);
        }
    
        public virtual ObjectResult<sp_ClienteBusquedaAdicciones_Result> sp_ClienteBusquedaAdicciones(string cedulaCLiente, string codigoAdiccion, string nombre, string apellido1, string apellido2)
        {
            var cedulaCLienteParameter = cedulaCLiente != null ?
                new ObjectParameter("CedulaCLiente", cedulaCLiente) :
                new ObjectParameter("CedulaCLiente", typeof(string));
    
            var codigoAdiccionParameter = codigoAdiccion != null ?
                new ObjectParameter("CodigoAdiccion", codigoAdiccion) :
                new ObjectParameter("CodigoAdiccion", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ClienteBusquedaAdicciones_Result>("sp_ClienteBusquedaAdicciones", cedulaCLienteParameter, codigoAdiccionParameter, nombreParameter, apellido1Parameter, apellido2Parameter);
        }
    
        public virtual ObjectResult<sp_CoberturaPolizaTodo_Result> sp_CoberturaPolizaTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CoberturaPolizaTodo_Result>("sp_CoberturaPolizaTodo");
        }
    
        public virtual ObjectResult<sp_CoberturaPolizaBuscaUna_Result> sp_CoberturaPolizaBuscaUna(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CoberturaPolizaBuscaUna_Result>("sp_CoberturaPolizaBuscaUna", nombreParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CatidadAdiccionesCliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CatidadAdiccionesCliente", cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CantidadAdiccionesCliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CantidadAdiccionesCliente", cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_AdiccionesClienteCantidad(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_AdiccionesClienteCantidad", cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CantidadAdiccionesCliente1(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CantidadAdiccionesCliente1", cedulaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_NIELS(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_NIELS", cedulaParameter);
        }
    
        public virtual ObjectResult<sp_nmm_Result> sp_nmm()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_nmm_Result>("sp_nmm");
        }
    
        public virtual ObjectResult<sp_CantidadAdCliente_Result> sp_CantidadAdCliente(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("Cedula", cedula) :
                new ObjectParameter("Cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CantidadAdCliente_Result>("sp_CantidadAdCliente", cedulaParameter);
        }
    
        public virtual int sp_InsertaRegistroPoliza(Nullable<double> monto_Asegurado, Nullable<double> porcentaje_Cobertura, Nullable<int> numero_Adicciones, Nullable<double> monto_Adicciones, Nullable<double> prima_Antes_Impuesto, Nullable<double> impuestos, Nullable<double> prima_Final, Nullable<int> iD_Cobertura_Poliza, string iD_Cliente, Nullable<System.DateTime> fecha_Vencimiento)
        {
            var monto_AseguradoParameter = monto_Asegurado.HasValue ?
                new ObjectParameter("Monto_Asegurado", monto_Asegurado) :
                new ObjectParameter("Monto_Asegurado", typeof(double));
    
            var porcentaje_CoberturaParameter = porcentaje_Cobertura.HasValue ?
                new ObjectParameter("Porcentaje_Cobertura", porcentaje_Cobertura) :
                new ObjectParameter("Porcentaje_Cobertura", typeof(double));
    
            var numero_AdiccionesParameter = numero_Adicciones.HasValue ?
                new ObjectParameter("Numero_Adicciones", numero_Adicciones) :
                new ObjectParameter("Numero_Adicciones", typeof(int));
    
            var monto_AdiccionesParameter = monto_Adicciones.HasValue ?
                new ObjectParameter("Monto_Adicciones", monto_Adicciones) :
                new ObjectParameter("Monto_Adicciones", typeof(double));
    
            var prima_Antes_ImpuestoParameter = prima_Antes_Impuesto.HasValue ?
                new ObjectParameter("Prima_Antes_Impuesto", prima_Antes_Impuesto) :
                new ObjectParameter("Prima_Antes_Impuesto", typeof(double));
    
            var impuestosParameter = impuestos.HasValue ?
                new ObjectParameter("Impuestos", impuestos) :
                new ObjectParameter("Impuestos", typeof(double));
    
            var prima_FinalParameter = prima_Final.HasValue ?
                new ObjectParameter("Prima_Final", prima_Final) :
                new ObjectParameter("Prima_Final", typeof(double));
    
            var iD_Cobertura_PolizaParameter = iD_Cobertura_Poliza.HasValue ?
                new ObjectParameter("ID_Cobertura_Poliza", iD_Cobertura_Poliza) :
                new ObjectParameter("ID_Cobertura_Poliza", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            var fecha_VencimientoParameter = fecha_Vencimiento.HasValue ?
                new ObjectParameter("Fecha_Vencimiento", fecha_Vencimiento) :
                new ObjectParameter("Fecha_Vencimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_InsertaRegistroPoliza", monto_AseguradoParameter, porcentaje_CoberturaParameter, numero_AdiccionesParameter, monto_AdiccionesParameter, prima_Antes_ImpuestoParameter, impuestosParameter, prima_FinalParameter, iD_Cobertura_PolizaParameter, iD_ClienteParameter, fecha_VencimientoParameter);
        }
    
        public virtual ObjectResult<sp_RegistroPolizaBusquedaID_Result> sp_RegistroPolizaBusquedaID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RegistroPolizaBusquedaID_Result>("sp_RegistroPolizaBusquedaID", iDParameter);
        }
    
        public virtual ObjectResult<sp_CoberturaPolizaBuscaID_Result> sp_CoberturaPolizaBuscaID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CoberturaPolizaBuscaID_Result>("sp_CoberturaPolizaBuscaID", iDParameter);
        }
    
        public virtual int sp_ModificaUnRegistroPoliza(Nullable<int> iD, Nullable<double> monto_Asegurado, Nullable<double> porcentaje_Cobertura, Nullable<int> numero_Adicciones, Nullable<double> monto_Adicciones, Nullable<double> pRima_Antes_Impuestos, Nullable<double> impuestos, Nullable<double> prima_Final, Nullable<int> iD_Cobertura_Poliza, string iD_Cliente, Nullable<System.DateTime> fecha_Vencimiento)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var monto_AseguradoParameter = monto_Asegurado.HasValue ?
                new ObjectParameter("Monto_Asegurado", monto_Asegurado) :
                new ObjectParameter("Monto_Asegurado", typeof(double));
    
            var porcentaje_CoberturaParameter = porcentaje_Cobertura.HasValue ?
                new ObjectParameter("Porcentaje_Cobertura", porcentaje_Cobertura) :
                new ObjectParameter("Porcentaje_Cobertura", typeof(double));
    
            var numero_AdiccionesParameter = numero_Adicciones.HasValue ?
                new ObjectParameter("Numero_Adicciones", numero_Adicciones) :
                new ObjectParameter("Numero_Adicciones", typeof(int));
    
            var monto_AdiccionesParameter = monto_Adicciones.HasValue ?
                new ObjectParameter("Monto_Adicciones", monto_Adicciones) :
                new ObjectParameter("Monto_Adicciones", typeof(double));
    
            var pRima_Antes_ImpuestosParameter = pRima_Antes_Impuestos.HasValue ?
                new ObjectParameter("PRima_Antes_Impuestos", pRima_Antes_Impuestos) :
                new ObjectParameter("PRima_Antes_Impuestos", typeof(double));
    
            var impuestosParameter = impuestos.HasValue ?
                new ObjectParameter("Impuestos", impuestos) :
                new ObjectParameter("Impuestos", typeof(double));
    
            var prima_FinalParameter = prima_Final.HasValue ?
                new ObjectParameter("Prima_Final", prima_Final) :
                new ObjectParameter("Prima_Final", typeof(double));
    
            var iD_Cobertura_PolizaParameter = iD_Cobertura_Poliza.HasValue ?
                new ObjectParameter("ID_Cobertura_Poliza", iD_Cobertura_Poliza) :
                new ObjectParameter("ID_Cobertura_Poliza", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            var fecha_VencimientoParameter = fecha_Vencimiento.HasValue ?
                new ObjectParameter("Fecha_Vencimiento", fecha_Vencimiento) :
                new ObjectParameter("Fecha_Vencimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificaUnRegistroPoliza", iDParameter, monto_AseguradoParameter, porcentaje_CoberturaParameter, numero_AdiccionesParameter, monto_AdiccionesParameter, pRima_Antes_ImpuestosParameter, impuestosParameter, prima_FinalParameter, iD_Cobertura_PolizaParameter, iD_ClienteParameter, fecha_VencimientoParameter);
        }
    
        public virtual int sp_RegistroPolizaModifica(Nullable<int> iD, Nullable<double> monto_Asegurado, Nullable<double> porcentaje_Cobertura, Nullable<int> numero_Adicciones, Nullable<double> monto_Adicciones, Nullable<double> pRima_Antes_Impuestos, Nullable<double> impuestos, Nullable<double> prima_Final, Nullable<int> iD_Cobertura_Poliza, string iD_Cliente, Nullable<System.DateTime> fecha_Vencimiento)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var monto_AseguradoParameter = monto_Asegurado.HasValue ?
                new ObjectParameter("Monto_Asegurado", monto_Asegurado) :
                new ObjectParameter("Monto_Asegurado", typeof(double));
    
            var porcentaje_CoberturaParameter = porcentaje_Cobertura.HasValue ?
                new ObjectParameter("Porcentaje_Cobertura", porcentaje_Cobertura) :
                new ObjectParameter("Porcentaje_Cobertura", typeof(double));
    
            var numero_AdiccionesParameter = numero_Adicciones.HasValue ?
                new ObjectParameter("Numero_Adicciones", numero_Adicciones) :
                new ObjectParameter("Numero_Adicciones", typeof(int));
    
            var monto_AdiccionesParameter = monto_Adicciones.HasValue ?
                new ObjectParameter("Monto_Adicciones", monto_Adicciones) :
                new ObjectParameter("Monto_Adicciones", typeof(double));
    
            var pRima_Antes_ImpuestosParameter = pRima_Antes_Impuestos.HasValue ?
                new ObjectParameter("PRima_Antes_Impuestos", pRima_Antes_Impuestos) :
                new ObjectParameter("PRima_Antes_Impuestos", typeof(double));
    
            var impuestosParameter = impuestos.HasValue ?
                new ObjectParameter("Impuestos", impuestos) :
                new ObjectParameter("Impuestos", typeof(double));
    
            var prima_FinalParameter = prima_Final.HasValue ?
                new ObjectParameter("Prima_Final", prima_Final) :
                new ObjectParameter("Prima_Final", typeof(double));
    
            var iD_Cobertura_PolizaParameter = iD_Cobertura_Poliza.HasValue ?
                new ObjectParameter("ID_Cobertura_Poliza", iD_Cobertura_Poliza) :
                new ObjectParameter("ID_Cobertura_Poliza", typeof(int));
    
            var iD_ClienteParameter = iD_Cliente != null ?
                new ObjectParameter("ID_Cliente", iD_Cliente) :
                new ObjectParameter("ID_Cliente", typeof(string));
    
            var fecha_VencimientoParameter = fecha_Vencimiento.HasValue ?
                new ObjectParameter("Fecha_Vencimiento", fecha_Vencimiento) :
                new ObjectParameter("Fecha_Vencimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RegistroPolizaModifica", iDParameter, monto_AseguradoParameter, porcentaje_CoberturaParameter, numero_AdiccionesParameter, monto_AdiccionesParameter, pRima_Antes_ImpuestosParameter, impuestosParameter, prima_FinalParameter, iD_Cobertura_PolizaParameter, iD_ClienteParameter, fecha_VencimientoParameter);
        }
    
        public virtual ObjectResult<sp_SelecionaAdiccionesClienteID_Result> sp_SelecionaAdiccionesClienteID(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SelecionaAdiccionesClienteID_Result>("sp_SelecionaAdiccionesClienteID", iDParameter);
        }
    
        public virtual ObjectResult<sp_PolizaBusqueda_Result> sp_PolizaBusqueda(string cedulaCLiente, string nombre, string apellido1, string apellido2)
        {
            var cedulaCLienteParameter = cedulaCLiente != null ?
                new ObjectParameter("CedulaCLiente", cedulaCLiente) :
                new ObjectParameter("CedulaCLiente", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PolizaBusqueda_Result>("sp_PolizaBusqueda", cedulaCLienteParameter, nombreParameter, apellido1Parameter, apellido2Parameter);
        }
    
        public virtual ObjectResult<sp_AdiccionesClienteReporte_Result> sp_AdiccionesClienteReporte(string cedulaCLiente, string nombre, string apellido1, string apellido2, string codigoAdiccion, string nombreAdiccion)
        {
            var cedulaCLienteParameter = cedulaCLiente != null ?
                new ObjectParameter("CedulaCLiente", cedulaCLiente) :
                new ObjectParameter("CedulaCLiente", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var codigoAdiccionParameter = codigoAdiccion != null ?
                new ObjectParameter("CodigoAdiccion", codigoAdiccion) :
                new ObjectParameter("CodigoAdiccion", typeof(string));
    
            var nombreAdiccionParameter = nombreAdiccion != null ?
                new ObjectParameter("NombreAdiccion", nombreAdiccion) :
                new ObjectParameter("NombreAdiccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AdiccionesClienteReporte_Result>("sp_AdiccionesClienteReporte", cedulaCLienteParameter, nombreParameter, apellido1Parameter, apellido2Parameter, codigoAdiccionParameter, nombreAdiccionParameter);
        }
    
        public virtual ObjectResult<sp_PolizaClienteReporte_Result> sp_PolizaClienteReporte(string cedulaCLiente, string nombre, string apellido1, string apellido2, string nombrePoliza, string descripcion)
        {
            var cedulaCLienteParameter = cedulaCLiente != null ?
                new ObjectParameter("CedulaCLiente", cedulaCLiente) :
                new ObjectParameter("CedulaCLiente", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var nombrePolizaParameter = nombrePoliza != null ?
                new ObjectParameter("NombrePoliza", nombrePoliza) :
                new ObjectParameter("NombrePoliza", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PolizaClienteReporte_Result>("sp_PolizaClienteReporte", cedulaCLienteParameter, nombreParameter, apellido1Parameter, apellido2Parameter, nombrePolizaParameter, descripcionParameter);
        }
    
        public virtual ObjectResult<sp_ReportePolizaCliente_Result> sp_ReportePolizaCliente(string cedulaCLiente, string nombre, string apellido1, string apellido2, string nombrePoliza, string descripcion)
        {
            var cedulaCLienteParameter = cedulaCLiente != null ?
                new ObjectParameter("CedulaCLiente", cedulaCLiente) :
                new ObjectParameter("CedulaCLiente", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apellido1Parameter = apellido1 != null ?
                new ObjectParameter("Apellido1", apellido1) :
                new ObjectParameter("Apellido1", typeof(string));
    
            var apellido2Parameter = apellido2 != null ?
                new ObjectParameter("Apellido2", apellido2) :
                new ObjectParameter("Apellido2", typeof(string));
    
            var nombrePolizaParameter = nombrePoliza != null ?
                new ObjectParameter("NombrePoliza", nombrePoliza) :
                new ObjectParameter("NombrePoliza", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ReportePolizaCliente_Result>("sp_ReportePolizaCliente", cedulaCLienteParameter, nombreParameter, apellido1Parameter, apellido2Parameter, nombrePolizaParameter, descripcionParameter);
        }
    }
}
