//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AseguradoraSiglo21.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Bitacora_Login = new HashSet<Bitacora_Login>();
        }
    
        public int ID { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasena { get; set; }
        public int Tipo_Usuario { get; set; }
    
        public virtual ICollection<Bitacora_Login> Bitacora_Login { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario1 { get; set; }
    }
}
